<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * The Layouts labels config.
 *
 * For deferred loading of layout labels, see `lib/functions/layout.php`.
 *
 * If child theme contains a `layouts-labels.php` config, it will be used
 * instead of this config.
 *
 * @since 3.6.0
 */
return [
	'content-sidebar'         => [
		'label' => __( 'Content, Primary Sidebar', 'genesis' ),
	],
	'sidebar-content'         => [
		'label' => __( 'Primary Sidebar, Content', 'genesis' ),
	],
	'content-sidebar-sidebar' => [
		'label' => __( 'Content, Primary Sidebar, Secondary Sidebar', 'genesis' ),
	],
	'sidebar-sidebar-content' => [
		'label' => __( 'Secondary Sidebar, Primary Sidebar, Content', 'genesis' ),
	],
	'sidebar-content-sidebar' => [
		'label' => __( 'Secondary Sidebar, Content, Primary Sidebar', 'genesis' ),
	],
	'full-width-content'      => [
		'label' => __( 'Full Width Content', 'genesis' ),
	],
];
